theme: jekyll-theme-minimal

title: Munindar Meena

logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS, Quant & Computational Finance
  <br>
  <strong><a target="_blank" href="https://www.gatech.edu">Georgia Tech</a></strong> 
  <br><br>
  BS, Electrical Engineering<br>
  Minor, Management Science<br>
  <strong><a target="_blank" href="https://www.iitmandi.ac.in/">IIT Mandi</a></strong> 
  
  <table width="100%">
            <tbody><tr>
                <td class="valign-top"><strong>location</strong></td>
                <td>Atlanta, GA 30308, USA.
                </td>
            </tr>
            <tr>
                <td class="valign-top"><strong>email</strong></td>
                <td>
                    mmeena3 [at] gatech.edu
                    <br> munindar.kumar [at] outlook.com
                    <br>
                </td>
            </tr>
            <tr>
                <td class="valign-top"><strong>phone</strong></td>
                <td>+1 (404) 901-3294</td>
            </tr>
            <tr>
                <td><strong>connect</strong></td>
                <td>
                    <a target="_blank" title="Github" href="https://www.github.com/munindarkr/"><img class="fa" src="https://img.icons8.com/fluent/25/000000/github.png"/></a>
                    <a target="_blank" title="Linkedin" href="https://www.linkedin.com/in/munindarkr/"><img class="fa" src="https://img.icons8.com/ios/25/000000/linkedin.png"></a>
                </td>
            </tr>
            <tr>
                <td><strong>resume</strong></td>
                <td>
                    <a href="docs/CV_Quant_Munindar_GeorgiaTech.pdf" download="">Download</a>&nbsp;
                </td>
            </tr>
        </tbody></table>